[package]
name = "telhecate"
version = "0.1.0"
authors = ["Alexandre Janniaux <alexandre.janniaux@gmail.com>"]

[dependencies]
telegram-bot = "0.5"
regex = "0.2"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
serde = "1.0"
serde_derive = "1.0"
